name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  job1:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  job2:
    name: CF_Nag
    runs-on: ubuntu-latest
    steps:
      - uses: stelligent/cfn_nag@master
        with:
          input_path: Templates
